### ISSUE TITLE
Add GalliumOS Support

### ISSUE THREAD

**Issue by EnterTheVoid-x86** [fetchcord/FetchCord#103]
I would love it if you added GalliumOS support.

**Comment by BlivionIaG** [comment]
Hello, can you provide a ```neofetch --stdout``` output ?

**Comment by EnterTheVoid-x86** [comment]
Sorry, no longer have galllium, but i can send someone else's stdout output

**Comment by EnterTheVoid-x86** [comment]
![image](https://user-images.githubusercontent.com/64978924/101191090-3bcf5500-3627-11eb-9c2d-87a84c681d90.png)

**Comment by EnterTheVoid-x86** [comment]
![image](https://user-images.githubusercontent.com/64978924/101191200-573a6000-3627-11eb-973f-6237d764825b.png)
v3.1

**Comment by BlivionIaG** [comment]
Second is close to unreadable ^^, I guess i can work with the first one, thanks.
